name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  EMAIL_USER: notused
  EMAIL_PASSWORD: notused
  DB_NAME: circle_test
  DB_USERNAME: ubuntu
  DB_PASSWORD:
  DJANGO_HOSTNAME: localhost:8000
  DJANGO_ALLOWED_HOSTS: '*'
  DJANGO_LOGFILE: /tmp/django.log
  SECRET_KEY: 'integration-test-only'
  DJANGO_SETTINGS_MODULE: happinesspackets.settings.ci

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/ci.txt
    - name: Collect static
      run: |
        python manage.py collectstatic --noinput
    - name: Run Tests
      run: |
        python manage.py test
